spring:
  application:
    name: document-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
